name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://bookYourMovie.github.io/
    steps:
      - name: deploy
        # ...deployment-specific steps
